### PR TITLE
Don't fail on empty diffs when running clang-format

### PR DESCRIPTION
**Pull request by peddie**

### CODE REVIEW

**Review by isaactorz — APPROVED** [review]

**Comment by isaactorz** [comment]
Would be good to see a test PR or something.

**Comment by peddie** [comment]
By a test PR, do you mean a PR adding a test to CI to check that this doesn't error, or a one-off PR showing that this has the desired behaviour in a downstream repo?

**Comment by isaactorz** [comment]
> By a test PR, do you mean a PR adding a test to CI to check that this doesn't error, or a one-off PR showing that this has the desired behaviour in a downstream repo?

Sorry, just circling back to this. Definitely the latter.

**Comment by peddie** [comment]
I'll try to think of the right situation.  This addresses a problem I observed locally (failure of clang-format-diff caused a script to stop), but I've not seen a failure in CI.

**Pull request merged**
